// Generated by npm run build:relay from src/server/relay/vercelEntry.ts. Do not edit.

// src/server/relay/vercelEntry.ts
import http from "node:http";

// src/server/relay/relayServer.ts
import { Server } from "socket.io";

// src/room/wire.ts
var ROOM_CODE_ALPHABET = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
var ROOM_CODE_LENGTH = 6;
function newRoomCode(random = defaultRandom) {
  const b = random(ROOM_CODE_LENGTH);
  let s = "";
  for (let i = 0; i < ROOM_CODE_LENGTH; i++) s += ROOM_CODE_ALPHABET[b[i] % ROOM_CODE_ALPHABET.length];
  return s;
}
function defaultRandom(n) {
  const b = new Uint8Array(n);
  globalThis.crypto.getRandomValues(b);
  return b;
}
function normalizeRoomCode(raw) {
  if (typeof raw !== "string") return null;
  const s = raw.trim().toUpperCase().replace(/[\s-]/g, "");
  if (s.length !== ROOM_CODE_LENGTH) return null;
  for (const ch of s) if (!ROOM_CODE_ALPHABET.includes(ch)) return null;
  return s;
}
var RELAY_PATH = "/api/relay/socket.io";
function toB64(u8) {
  if (typeof Buffer !== "undefined") return Buffer.from(u8.buffer, u8.byteOffset, u8.byteLength).toString("base64");
  let s = "";
  for (let i = 0; i < u8.length; i++) s += String.fromCharCode(u8[i]);
  return btoa(s);
}
function fromB64(s) {
  if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(s, "base64"));
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function encodeWire(v) {
  return JSON.stringify(v, (_k, x) => {
    if (x instanceof ArrayBuffer) return { __b64: toB64(new Uint8Array(x)) };
    if (ArrayBuffer.isView(x)) return { __b64: toB64(new Uint8Array(x.buffer, x.byteOffset, x.byteLength)), u8: 1 };
    if (x && typeof x === "object" && x.type === "Buffer" && Array.isArray(x.data)) {
      return { __b64: toB64(Uint8Array.from(x.data)), u8: 1 };
    }
    return x;
  });
}
function decodeWire(s) {
  return JSON.parse(s, (_k, x) => {
    if (x && typeof x === "object" && typeof x.__b64 === "string") {
      const u8 = fromB64(x.__b64);
      return x.u8 ? u8 : u8.buffer.slice(u8.byteOffset, u8.byteOffset + u8.byteLength);
    }
    return x;
  });
}

// src/server/relay/Broker.ts
import { Redis } from "ioredis";
var MemoryBroker = class {
  kind = "memory";
  subs = /* @__PURE__ */ new Map();
  kv = /* @__PURE__ */ new Map();
  async publish(channel, payload) {
    const set = this.subs.get(channel);
    if (!set) return;
    for (const fn of [...set]) queueMicrotask(() => fn(payload));
  }
  async subscribe(channel, fn) {
    let set = this.subs.get(channel);
    if (!set) this.subs.set(channel, set = /* @__PURE__ */ new Set());
    set.add(fn);
    return async () => {
      set.delete(fn);
      if (!set.size) this.subs.delete(channel);
    };
  }
  live(key2) {
    const e = this.kv.get(key2);
    if (!e) return null;
    if (Date.now() > e.until) {
      this.kv.delete(key2);
      return null;
    }
    return e;
  }
  async setNx(key2, value, ttlSec) {
    if (this.live(key2)) return false;
    this.kv.set(key2, { v: value, until: Date.now() + ttlSec * 1e3 });
    return true;
  }
  async get(key2) {
    return this.live(key2)?.v ?? null;
  }
  async expire(key2, ttlSec) {
    const e = this.live(key2);
    if (e) e.until = Date.now() + ttlSec * 1e3;
  }
  async del(key2) {
    this.kv.delete(key2);
  }
  async close() {
    this.subs.clear();
  }
};
var RedisBroker = class {
  kind = "redis";
  cmd;
  sub;
  handlers = /* @__PURE__ */ new Map();
  constructor(url) {
    const opts = { maxRetriesPerRequest: 3, enableAutoPipelining: true, lazyConnect: false };
    this.cmd = new Redis(url, opts);
    this.sub = new Redis(url, opts);
    this.sub.on("message", (channel, payload) => {
      for (const fn of this.handlers.get(channel) ?? []) fn(payload);
    });
    for (const c of [this.cmd, this.sub]) c.on("error", (e) => console.error("[relay] redis", e.message));
  }
  async publish(channel, payload) {
    await this.cmd.publish(channel, payload);
  }
  async subscribe(channel, fn) {
    let set = this.handlers.get(channel);
    if (!set) {
      this.handlers.set(channel, set = /* @__PURE__ */ new Set());
      await this.sub.subscribe(channel);
    }
    set.add(fn);
    return async () => {
      set.delete(fn);
      if (!set.size) {
        this.handlers.delete(channel);
        await this.sub.unsubscribe(channel).catch(() => void 0);
      }
    };
  }
  async setNx(key2, value, ttlSec) {
    return await this.cmd.set(key2, value, "EX", ttlSec, "NX") === "OK";
  }
  async get(key2) {
    return this.cmd.get(key2);
  }
  async expire(key2, ttlSec) {
    await this.cmd.expire(key2, ttlSec);
  }
  async del(key2) {
    await this.cmd.del(key2);
  }
  async close() {
    this.cmd.disconnect();
    this.sub.disconnect();
  }
};
function brokerFromEnv(env = process.env) {
  const url = env.REDIS_URL || env.KV_URL || env.UPSTASH_REDIS_URL;
  return url ? new RedisBroker(url) : new MemoryBroker();
}

// src/server/relay/RelayCore.ts
var key = (code) => `rr:room:${code}`;
var hostCh = (code) => `rr:h:${code}`;
var peerCh = (code, pid) => `rr:p:${code}:${pid}`;
var roomCh = (code) => `rr:b:${code}`;
var PEER_KEY = /^[a-z0-9]{8,64}$/i;
var RelayCore = class {
  broker;
  ttl;
  beat;
  /** Channels with a subscriber on this instance: delivered locally without a broker hop. */
  local = /* @__PURE__ */ new Map();
  rooms = 0;
  constructor(io, broker, opts = {}) {
    this.broker = broker;
    this.ttl = opts.roomTtlSec ?? 90;
    this.beat = opts.heartbeatSec ?? 20;
    io.on("connection", (s) => {
      const q = s.handshake.query;
      if (q.role === "host") void this.onHost(s, q);
      else if (q.role === "peer") void this.onPeer(s, q);
      else s.disconnect(true);
    });
  }
  /** Room exists (a host created it and it has not expired or been closed). */
  async roomExists(code) {
    return await this.broker.get(key(code)) !== null;
  }
  async route(channel, msg) {
    const here = this.local.get(channel);
    if (here) return here(msg);
    await this.broker.publish(channel, encodeWire(msg));
  }
  async listen(channel, fn, localOnly = true) {
    if (localOnly) this.local.set(channel, fn);
    const off = await this.broker.subscribe(channel, (p) => fn(decodeWire(p)));
    return async () => {
      if (this.local.get(channel) === fn) this.local.delete(channel);
      await off();
    };
  }
  // ---------------------------------------------------------------- host
  async onHost(s, q) {
    let code = normalizeRoomCode(q.room);
    const secret = typeof q.secret === "string" && q.secret.length >= 16 ? q.secret : null;
    if (code && secret) {
      const cur = await this.broker.get(key(code));
      if (cur !== null && JSON.parse(cur).secret !== secret) {
        s.emit("relayError", { code: "ROOM_TAKEN", message: "That room belongs to another host." });
        s.disconnect(true);
        return;
      }
      if (cur === null && !await this.broker.setNx(key(code), JSON.stringify({ secret }), this.ttl)) {
        s.emit("relayError", { code: "ROOM_TAKEN", message: "That room code is in use." });
        s.disconnect(true);
        return;
      }
    } else {
      const fresh = randomSecret();
      code = null;
      for (let i = 0; i < 12 && !code; i++) {
        const c = newRoomCode();
        if (await this.broker.setNx(key(c), JSON.stringify({ secret: fresh }), this.ttl)) code = c;
      }
      if (!code) {
        s.emit("relayError", { code: "NO_ROOM", message: "Could not allocate a room. Try again." });
        s.disconnect(true);
        return;
      }
      q = { ...q, secret: fresh };
    }
    const roomCode = code;
    const hostSecret = q.secret ?? secret;
    if (!s.connected) return;
    this.rooms++;
    let closed = false;
    const off = await this.listen(hostCh(roomCode), (m) => {
      const msg = m;
      if (msg.k === "n") s.emit("notice", msg.n);
      else s.emit("pm", msg.pid, msg.f.ev, msg.f.args, msg.f.ack ?? null);
    });
    const heartbeat = setInterval(() => void this.broker.expire(key(roomCode), this.ttl), this.beat * 1e3);
    s.on("hm", (pid, ev, args) => {
      if (typeof pid !== "string" || typeof ev !== "string" || !Array.isArray(args)) return;
      void this.route(peerCh(roomCode, pid), { k: "f", f: { ev, args } });
    });
    s.on("ha", (pid, ack, args) => {
      if (typeof pid !== "string" || typeof ack !== "number" || !Array.isArray(args)) return;
      void this.route(peerCh(roomCode, pid), { k: "f", f: { ack, args } });
    });
    s.on("close", (reason) => {
      closed = true;
      void this.broker.publish(roomCh(roomCode), encodeWire({ k: "n", n: { t: "closed", reason: typeof reason === "string" ? reason.slice(0, 120) : "The host closed the room." } }));
      void this.broker.del(key(roomCode));
      s.disconnect(true);
    });
    s.on("disconnect", () => {
      clearInterval(heartbeat);
      this.rooms--;
      void off();
      if (!closed) void this.broker.publish(roomCh(roomCode), encodeWire({ k: "n", n: { t: "hostgone" } }));
    });
    s.emit("room", { code: roomCode, secret: hostSecret });
    void this.broker.publish(roomCh(roomCode), encodeWire({ k: "n", n: { t: "hostback" } }));
  }
  // ---------------------------------------------------------------- peers
  async onPeer(s, q) {
    const code = normalizeRoomCode(q.room);
    const pid = typeof q.key === "string" && PEER_KEY.test(q.key) ? q.key : null;
    if (!code || !pid || !await this.roomExists(code)) {
      s.emit("relayError", { code: "ROOM_NOT_FOUND", message: code ? `Room ${code} was not found. It may have closed.` : "That is not a valid room code." });
      s.disconnect(true);
      return;
    }
    await this.route(peerCh(code, pid), { k: "x" });
    if (!s.connected) return;
    const offPeer = await this.listen(peerCh(code, pid), (m) => {
      const msg = m;
      if (msg.k === "x") {
        s.disconnect(true);
        return;
      }
      if (msg.f.ack !== void 0) s.emit("a", msg.f.ack, msg.f.args);
      else s.emit("m", msg.f.ev, msg.f.args);
    });
    const offRoom = await this.listen(roomCh(code), (m) => s.emit("notice", m.n), false);
    s.on("m", (ev, args, ack) => {
      if (typeof ev !== "string" || !Array.isArray(args)) return;
      const f = { ev, args };
      if (typeof ack === "number") f.ack = ack;
      void this.route(hostCh(code), { k: "f", pid, f });
    });
    s.on("disconnect", () => {
      void offPeer();
      void offRoom();
      void this.route(hostCh(code), { k: "n", n: { t: "close", pid } });
    });
    s.emit("joined", { code });
    void this.route(hostCh(code), { k: "n", n: { t: "open", pid } });
  }
};
function randomSecret() {
  const b = new Uint8Array(24);
  globalThis.crypto.getRandomValues(b);
  return Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
}

// src/server/relay/relayServer.ts
function parseAllowedOrigins(v) {
  return (v ?? "").split(",").map((s) => s.trim().replace(/\/+$/, "")).filter(Boolean);
}
function originAllowed(origin, allowed) {
  if (!allowed.length) return true;
  return !!origin && allowed.includes(origin);
}
function attachRelay(servers, broker = brokerFromEnv(), opts = {}, allowedOrigins = parseAllowedOrigins(process.env.RELAY_ALLOWED_ORIGINS)) {
  const io = new Server({
    path: RELAY_PATH,
    // Vercel Functions carry Socket.IO over WebSocket only (no HTTP long-polling).
    transports: ["websocket"],
    serveClient: false,
    cors: { origin: false },
    maxHttpBufferSize: 256 * 1024,
    // WebSocket upgrades are not subject to CORS: browsers send Origin, and the relay only admits
    // the configured client origins (RELAY_ALLOWED_ORIGINS) when that list is set.
    allowRequest: (req, cb) => cb(null, originAllowed(req.headers.origin, allowedOrigins)),
    pingInterval: 1e4,
    pingTimeout: 12e3
  });
  for (const s of servers) io.attach(s);
  return new RelayCore(io, broker, opts);
}
function normalizeRelayUrl(url) {
  const u = url ?? "/";
  if (u.startsWith(RELAY_PATH)) return u;
  const i = u.indexOf("/socket.io");
  return i >= 0 ? RELAY_PATH + u.slice(i + "/socket.io".length) : u;
}

// src/server/relay/vercelEntry.ts
var server = http.createServer((req, res) => {
  if ((req.url ?? "").includes("/health")) {
    res.setHeader("content-type", "application/json");
    res.setHeader("cache-control", "no-store");
    res.end(JSON.stringify({ ok: true, broker: relay.broker.kind, rooms: relay.rooms }));
    return;
  }
  res.statusCode = 404;
  res.end("Pizzeria Roadrash room relay");
});
var relay = attachRelay([server]);
for (const ev of ["request", "upgrade"]) {
  server.prependListener(ev, (req) => {
    req.url = normalizeRelayUrl(req.url);
  });
}
var vercelEntry_default = server;
export {
  vercelEntry_default as default
};
